"""add operations

Revision ID: ef68524edda9
Revises: 47a09671e222
Create Date: 2025-12-18 00:04:39.382100

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ef68524edda9"
down_revision: Union[str, Sequence[str], None] = "47a09671e222"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 前処理
    pre_upgrade()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operations",
        sa.Column("operation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "operation_type", sa.Integer(), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "STARTED",
                "COMPLETED",
                "ERROR",
                name="operation_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "reason", sa.String(length=256), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "operation_id", name=op.f("pk_operations")
        ),
    )
    # ### end Alembic commands ###
    # 後処理
    post_upgrade()


def downgrade() -> None:
    """Downgrade schema."""
    # 前処理
    pre_downgrade()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("operations")
    # ### end Alembic commands ###
    # 後処理
    post_downgrade()


def pre_upgrade() -> None:
    # スキーマ更新前に実行する必要がある処理
    pass


def post_upgrade() -> None:
    # スキーマ更新後に実行する必要がある処理
    pass


def pre_downgrade() -> None:
    # スキーマ更新前に実行する必要がある処理
    pass


def post_downgrade() -> None:
    # スキーマ更新後に実行する必要がある処理
    pass
