"""add initial_tables

Revision ID: 47a09671e222
Revises: 11e4c4841c14
Create Date: 2025-11-30 00:12:19.566028

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "47a09671e222"
down_revision: Union[str, Sequence[str], None] = "11e4c4841c14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 前処理
    pre_upgrade()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "todos",
        sa.Column("todo_id", sa.Uuid(), nullable=False),
        sa.Column(
            "title", sa.String(length=256), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "IN_PROGRESS",
                "COMPLETED",
                name="status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "todo_id", name=op.f("pk_todos")
        ),
    )
    op.create_table(
        "subtasks",
        sa.Column("subtask_id", sa.Uuid(), nullable=False),
        sa.Column(
            "title", sa.String(length=256), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "IN_PROGRESS",
                "COMPLETED",
                name="status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("todo_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["todo_id"],
            ["todos.todo_id"],
            name=op.f("fk_subtasks_todo_id_todos"),
        ),
        sa.PrimaryKeyConstraint(
            "subtask_id", name=op.f("pk_subtasks")
        ),
    )
    op.create_index(
        op.f("ix_subtasks_todo_id"),
        "subtasks",
        ["todo_id"],
        unique=False,
    )
    # ### end Alembic commands ###
    # 後処理
    post_upgrade()


def downgrade() -> None:
    """Downgrade schema."""
    # 前処理
    pre_downgrade()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_subtasks_todo_id"), table_name="subtasks"
    )
    op.drop_table("subtasks")
    op.drop_table("todos")
    # ### end Alembic commands ###
    # 後処理
    post_downgrade()


def pre_upgrade() -> None:
    # スキーマ更新前に実行する必要がある処理
    pass


def post_upgrade() -> None:
    # スキーマ更新後に実行する必要がある処理
    pass


def pre_downgrade() -> None:
    # スキーマ更新前に実行する必要がある処理
    pass


def post_downgrade() -> None:
    # スキーマ更新後に実行する必要がある処理
    pass
